### ISSUE TITLE
Upstream changed, SSL certificate invalid for old upstream

### ISSUE THREAD

**Issue by tastytea** [stefan-langenmaier/ring-overlay#68]
net-voip/ring-daemon-99999999 tries to fetch from <https://gerrit-ring.savoirfairelinux.com/ring-daemon/>, the certificate was valid until 2019-11-10.

New upstream is:
net-voip/ring-daemon: <https://git.jami.net/savoirfairelinux/ring-daemon.git>
net-libs/libringclient: <https://git.jami.net/savoirfairelinux/ring-lrc.git>
net-voip/gnome-ring: <https://git.jami.net/savoirfairelinux/ring-client-gnome.git>

**Comment by stefan-langenmaier** [comment]
Hi @tastytea ,

thanks for the feedback. I updated the references, but I cannot vouch for the live ebuilds at this moment. I doubt they will build. A lot has changed since they ware used by me that last time.

Of course I'd be happy to receive feedback and improvements for them but for now I try to stabilize the ebuild for the last tarball release.

Best regards,
Stefan
